name: Hello Agile

on:
  push:
    branches: [dev]       # Runs only when pushing to 'dev' branch
  pull_request:
    branches: [main]      # Runs when a PR targets 'main'

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Hello from GitHub Actions triggered by ${{ github.event_name }}!"

